mysql:
  user: root
  pass: wzqadzlc520
  host: 127.0.0.1
  port: 3306
  dbname: douyin
  charset: utf8mb4
  parsetime: True
  loc: Local

redis:
  host : 127.0.0.1
  port : 6379
  pass :

ip : 10.250.36.248

ffmpeg : D:\douyin\simple-demo-main\middleware\ffmpeg\ffmpeg.exe