mysql:
  user: root
  pass: qwerqwer1214
  host: 127.0.0.1
  port: 3306
  dbname: douyin
  charset: utf8mb4
  parsetime: True
  loc: Local

redis:
  host : 127.0.0.1
  port : 6379
  pass :

ip : 222.20.100.159

ffmpeg : C:\Users\lc\Desktop\DouyinOrigin\middleware\ffmpeg\ffmpeg.exe