mysql:
  user: root
  pass: zlc020706
  host: 127.0.0.1
  port: 3306
  dbname: douyin
  charset: utf8mb4
  parsetime: True
  loc: Local

redis:
  host : 127.0.0.1
  port : 6379
  pass :

ip : 10.133.144.123

ffmpeg : C:\Users\lc\Desktop\DouyinOrigin\middleware\ffmpeg\ffmpeg.exe